name: Build and deploy Python app to Azure Web App - pls20240920173633

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Switch to Linux (or keep Windows if you prefer)
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip the application files
        run: zip -r app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ./app.zip

  deploy:
    runs-on: ubuntu-latest  # You can use 'windows-latest' if necessary, but Linux is common for Python

    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_00000002-0000-0000-c000-000000000000 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_3c654404-49ac-4abc-9fd1-563fbf81abea }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_13d9d7b3-23bf-4145-a004-395bfc117df1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pls20240920173633'  # Replace with your app service name
          slot-name: 'Production'
          package: './app.zip'
