trigger:
- main  # Or your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Adjust according to your Python version

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python manage.py collectstatic --noinput  # If you're using Django; adjust as necessary for Flask
  displayName: 'Collect static files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureSubscriptionName'  # Replace with your Azure subscription
    appName: 'AppServiceName'  # Replace with your App Service name
    package: '$(Build.ArtifactStagingDirectory)/app.zip'

          
